version: '3'
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/client/src
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - WATCHPACK_POLLING=true

  server:
    build:
      context: ./server
    volumes:
      - ./server/src:/app/src
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server

volumes:
  db:
  pgadmin: