version: '3'
services:
  client:
    volumes:
      - ./client/src:/client/src
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - ENV=DEV
      - WATCHPACK_POLLING=true

  server:
    build:
      context: ./server
    volumes:
      - ./server/src:/app/src
    environment:
      - API_PORT=3001
      - API_PREFIX=/api
      - PGHOST=db
      - PGPORT=5432
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - ENV=DEV
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=project
    ports:
      - "3001:3001"
    depends_on:
      - db

  bucket:
    build:
      context: ./bucket
    volumes:
      - ./bucket/src:/app/src
      - /app/uploads
    ports:
      - "3002:3002"
    environment:
      - ENV=DEV
      - API_PORT=3002
      - API_PREFIX=/bucket

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  db:
  pgadmin: